[build]
  publish = "dist/employee-management-frontend"
  command = "npm run build -- --configuration production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run start"
  port = 4200
  targetPort = 4200
  publish = "dist/employee-management-frontend"
